### ISSUE TITLE
Only publish to Gitlab registry

### ISSUE THREAD

**Issue by fbjerggaard** [droidsolutions/semantic-release-nuget#203]
I have a need for publishing a package only to the GitLab registry, therefore I suggest adding a variable `publishToNuget` which defaults to true but allows the user to specify where to publish the package to.

The way I see it, it should just be wrapping the following in an if-statement to check if the package should be published there.
Alternatively it could check whether `pluginConfig.nugetServer` is null - but that would break the current implementation.

https://github.com/droidsolutions/semantic-release-nuget/blob/238a029da65b58758c797e66ad76e96df4b27384/src/publish.ts#L16-L38

I am happy to provide a PR if this is a feature that is wanted.

**Comment by Kampfmoehre** [comment]
You could just overwrite nugetServer in config like described in [the Readme](https://github.com/droidsolutions/semantic-release-nuget#options) but I guess that would not work with environment variables like CI_SERVER_URL.

**Comment by fbjerggaard** [comment]
Yeah, I did think about that, but that would require a lot of workarounds to get it to work as smoothly and easily as just setting `publishToGitlab` to true :)

**Comment by Kampfmoehre** [comment]
@fbjerggaard I think I managed to implement it, are you able to test it directly from the branch (by replacing package name with a git Url in package-json)  or do you need a published NPM package?

**Comment by fbjerggaard** [comment]
@Kampfmoehre Seems like I would need a published NPM package since `npm install https://github.com/droidsolutions/semantic-release-nuget.git#gitlab_only` doesn't build the files

**Comment by Kampfmoehre** [comment]
I see, let's just publish it then as beta

**Comment by fbjerggaard** [comment]
Seems to work perfectly - the only issue I ran into was that it still required the `NUGET_TOKEN` variable to be set even though it is not neccessary.

**Comment by Kampfmoehre** [comment]
This will be resolved in the final version, I'll wait a little bit until another issue that is also in the beta branch is resolved then I'll merge to release a final version.

**Comment by fbjerggaard** [comment]
Awesome - thanks a lot for the prompt responses!

**Comment by Kampfmoehre** [comment]
This is included in [v1.2.0](https://github.com/droidsolutions/semantic-release-nuget/releases/tag/v1.2.0).
