### ISSUE TITLE
[Feature] Convert semantic-release/commit-analyzer rules to GitVersion

### ISSUE THREAD

**Issue by BinToss** [droidsolutions/semantic-release-nuget#604]
Admittedly, this request might be outside the scope of this plugin.

Although I like GitVersion's generated version variables and strings and its runtime API, managing its commit message and branch rules to match Semantic Release's rules (and vice versa) is a constant battle. Doing this for multiple repositories makes it all feel like a waste of time.
While Semantic Release prefers Angular commit convention and no particular branching strategy, GitVersion is set up for GitFlow/GitHubFlow branching strategies by default. It's default commit message patterns are Semver.
```yml
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
```

It's possible to manually define RegEx patterns producing version info similar to Semantic Release, but more complex patterns are difficult to manually define while conforming to one's Semantic Release configuration.

# Implementation Notes

> The following code snippets are json-schema pseudo-code

- It may be best to hold off on this until GitVersion's schema for `GitVersion.yml` is submitted to schemastore.org. This will probably happen as part of GitVersion 6.0.0's release. The schema is included with 
- By default, do not patch `GitVersion.yml`
  ```json
  "gitVersionPatchConfig": {
    "type": "boolean",
    "description": "Boolean indicating whether semantic-release-nuget should overwrite the rules in GitVersion's config file(s) with the rules determined by semantic-release/commit-analyzer.",
    "default": false
  },
  ```
- Configuration for patching GitVersion config file...
  - default path(s): `**/GitVersion.yml` (glob).
    - Usually in repo root or .NET projects' folders. NOTE: monorepos may contain multiple configs—one per project.
    - Allow users to specify GitVersion.yml path(s) (String array?). Ignore/skip default glob pattern when this is defined.
    ```json
    "gitVersionConfigPath": {
      "type": "array",
      "items": {
          "type": "string"
      },
      "description": "A full or relative path to a GitVersion.yml, or a Glob pattern to find one or more.",
      "default": ["**/GitVersion.yml"]
    },
    ```
  - Treat GitVersion.yml in Git submodules as read-only.
  - Allow users to manually initiate a config patch via `npx`/`npm run {script}`
  - Optionally patch in `chore(release): *` commits.
    ```json
    "gitVersionPatchConfigInReleases": {
      "type": "boolean",
      "description": "A boolean indicating if semantic-release-nuget should patch the GitVersion's config(s) in the next `chore(release):` commit.",
      "default": false
    }
    ```

# References

- semantic-release/commit-analyzer uses [micromatch](https://github.com/micromatch/micromatch#matching-features) for Glob support.
- [GitVersion's suggested conventional commit message RegEx patterns](https://gitversion.net/docs/reference/version-increments#conventional-commit-messages). At the time of writing, the suggested PATCH pattern is erroneously increments for insignificant commit types e.g. chore, test, ci.
- [GitVersion Configuration](https://gitversion.net/docs/reference/configuration)

**Comment by Kampfmoehre** [comment]
Hi, thank you for the feature request.

I am not very familiar with GitVersion, are you requesting that this Semantic Release plugin should update the GitVersion configuration file? If yes, what would the use case be? As far as I understand GitVersion is an alternative to Semantic Release and running them both at the same time does not seem to have any benefit.

If yo uonly want to update a version string in a (yaml) file you could take a look at the [semantic-release-update-file plugin](https://github.com/droidsolutions/semantic-release-update-file) .

**Comment by BinToss** [comment]
Currently, I only use GitVersion's `GitVersion.MSBuild` NuGet package for versioning local builds and for code-generating and injecting various convenient [version variables](https://gitversion.net/docs/reference/variables) into libraries and apps as properties/fields. I have it properly configured in some projects to produce the same version as Semantic Release *most of the time*. There's some differences between their "git branch" rules that I haven't sorted out yet.

 Although its sister-project GitReleaseManager could be utilized for the release/publish stage, its commit message analysis, changelog generation, and release notes generation are...primitive compared to Semantic Release. Out-of-the-box, that is. 

```
| Semantic Release / Conventional Changelog | GitVersion.MSBuild
| -------------------------------------------- | --------------------
- The GitTools projects lack the equivalent of NodeJS projects' `extends` configuration capability.
- Semantic Release utilizes [Conventional Changelog](https://github.com/conventional-changelog/conventional-changelog) for presets. GitTools' projects do not ship with support equivalents. Conventional Commits and similar standards–supported as presets in Conventional Changelog–are barely supported (by community submissions) in the form of a [single header](https://gitversion.net/docs/reference/version-increments#conventional-commit-messages) with a ([currently incorrect](https://github.com/GitTools/GitVersion/pull/3628)) configuration example) in GitVersion's documentation.
- Conventional Changelog's presets' schemas are well-defined in JSON format.

I was hoping to avoid spending potentially weeks on "reinventing the wheel", so to speak. Semantic Release and Conventional Changelog already exist so it would-in theory-be more efficient to utilize them than recreate them for GitVersion.

----

P.S. The use case and purpose of this feature request aren't directly related to semantic-release-nuget, though the resulting plugin would likely be used in conjunction with semantic-release-nuget.

**Comment by Kampfmoehre** [comment]
I'm sorry but I still don't understand what exactly you want this plugin to do.

If you just want to have some of the variables Semantic Release generates you can export them with the help of the [Semantic Release Exec plugin](https://github.com/semantic-release/exec). For example you could use this configuration to export the Commit Hash of the release commit and the version number:

```js
{
  successCmd:
    'echo "RELEASE_VERSION=${nextRelease.version}" >> release.env && echo "RELEASE_SHA=${nextRelease.gitHead}" >> release.env'
}
```

This `release.env` file could then be used by various CI tools to pass to the next job as environment variables.

If you want GitVersion to behave more like Semantic Release you should open a Feature Request there.

If you want GitVersion to generate release variables from a Semantic Release version you could try to use the [update-file-plugin](https://github.com/droidsolutions/semantic-release-update-file) as mentioned, though I am not sure if you can manipulate GitVersion this easily.

**Comment by BinToss** [comment]
~~So, I discovered the GitInfo NuGet package which is very similar to GitVersion—minus generation of the Version build variable.~~
Too bad its dependencies violate GDPR...
----

On the subject of what I want from `semantic-release-nuget`: nothing to "solve" this issue. What I wish we had is outside the scope of semantic-release-nuget and should instead be a separate project. 
When I created this Issue, I was tired and submitted my cry for help to the first place I could find where someone may be willing to help. It seemed like a good idea at the time. 
In hindsight, not so much.

Thanks for putting up with this...weirdness.

**Comment by Kampfmoehre** [comment]
Sorry to hear we can not help you. I am still unsure if I understand correctly what exactly you need, but you can take a look at the [Semantic Release configuration we use for our Semantic Version NuGet package](https://github.com/droidsolutions/semantic-version/blob/main/package.json#L53-#L115).
This uses the update-file plugin to update the commit hash in the Directory.build.props which then lands in the resulting NuGet package. Feel free to reopen if there is anything else we can add to this plugin that you might find useful.
