### ISSUE TITLE
Publish Step is not compatible with Windows

### ISSUE THREAD

**Issue by JeremyWildsmith** [droidsolutions/semantic-release-nuget#686]
Hello,

semantic-release-nuget's publish step doesn't work with GitHub actions using the windows-latest image because this line (referenced below) generates an invalid path on Windows (causing the publish step to fail.) This is due to the hard-coded forward slash, which should be a backslash on windows.

https://github.com/droidsolutions/semantic-release-nuget/blob/96efded87a9ec4ef2449cdc0c66c1c06a804bea6/src/publish.ts#L22

**Comment by Kampfmoehre** [comment]
@JeremyWildsmith can you test if it works with [2.0.0-beta.1](https://github.com/droidsolutions/semantic-release-nuget/releases/tag/v2.0.0-beta.1)

**Comment by JeremyWildsmith** [comment]
Hello,

Thanks for the quick reply!

I’ll try to allocate some time this afternoon to take a look and let you know.
