### ISSUE TITLE
Nuget Source Conflict

### ISSUE THREAD

**Issue by nerumo** [droidsolutions/semantic-release-nuget#777]
I'm having a special scenario, which leads to an error during publish. I use a central gitlab project as a package registry, lets call it "registry project". I have a project A, that depends on a nuget Package that is in the "registry project". So for building the project, I need a nuget.config, that contains the package source "https://gitlab.com/api/v4/projects/<registry-project>/packages/nuget/index.json". 

It's the same url, that is needed for pushing project A to the project. Now the `dotnet nuget add source` command failes because of a conflict: `error: The source specified has already been added to the list of available package sources. Provide a unique source.`. I did not find a way to hack my way around it.

Could you make the `dotnet nuget add source` command optional? This would allow me to control the nuget.config myself. Alternatively, allow the add source command to fail if that error message appears (but feels a bit magic to me)

Could I support you in any way? Thank you already for all your work you put into this

**Comment by Kampfmoehre** [comment]
Yes that might work, I will see if I can add that in the next days

**Comment by nerumo** [comment]
it worked, thank you! :muscle: 

as a sidenote: if the nuget config already contains the source, the source must be named "gitlab". it would be possible to read that from the output as well (without `--format short`), but the parsing of this is rather ugly and probably not worth the effort.

**Comment by Kampfmoehre** [comment]
Hm that could be a problem. I guess instead of parsing command output we could also just check the nuget.config file but that would not work if the config is set somehwere else. I will see if I can come up with some Regex for parsing the output.
